name: Build Docker Image

on:
  push:
    branches:
      - master  # Change this to your preferred branch

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v2

    - name: Build Docker image
      run: docker build -t your-docker-image-name:latest .
        

    - name: Push Docker image
      run: docker push your-docker-image-name:latest
